### PR TITLE
Cl ireland

### PR DESCRIPTION
**Pull request by C-Red20**
Added style to ireland.css
-Changes all three divs to columns and added borders and fixed picture sizes. 
-Added a section to allow movement of columns. 

fixed code in main.js to allow multiple .innerHTML

### CODE REVIEW

**Comment by Iris-Lee4** [comment]
looking good!!

**Comment by DeVanteFarmer** [comment]
Looks absolutely fantastic!

**Comment by benbower44** [comment]
looks ugl..... i mean good

**Comment by dmaceylewis** [comment]
hideous... GREAT! :)

**Pull request merged**
